FROM rust:1.67 AS builder
ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR
RUN apt update && apt install build-essential git curl python3-pip python3-dev ffmpeg libssl-dev libffi-dev -y
RUN git clone https://github.com/tikion/tikion.git \&&
    cd tikion \&&
    pip install -r requirements.txt \&&
    pip install .
RUN pip install --upgrade --no-cache-dir pip && pip install --no-cache-dir -r requirements.txt
