# 第一阶段：构建镜像
FROM python:3.10-slim-bullseye AS builder

ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-utils \
        build-essential \
        curl \
        git \
        python3-dev \
        python3-pip \
        ffmpeg

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    export PATH="$HOME/.cargo/bin:$PATH" && \
    pip install --upgrade pip && \
    pip wheel --wheel-dir=/root/wheels -r requirements.txt && \
    rm -rf /root/.cargo /root/.cache /root/.local /var/cache/apt/* /var/lib/apt/lists/* && \
    rm -rf /app

# 第二阶段：构建最终镜像
FROM python:3.10-slim-bullseye

ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR
COPY --from=builder /root/wheels /root/wheels

RUN apt-get update && \
    apt-get install -y --no-install-recommends git ffmpeg && \
    pip install --no-cache-dir --find-links=/root/wheels -r requirements.txt && \
    rm -rf /root/wheels /var/cache/apt/* /var/lib/apt/lists/*

