FROM python:3.10-slim-bullseye
ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR
RUN apt-get update && apt-get install -y gcc curl uild-essential git python3-pip python3-dev ffmpeg 
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && apt-get install --reinstall libc6-dev -y
ENV PATH="/root/.cargo/bin:${PATH}"
##RUN pip install --upgrade pip && pip install tiktoken
RUN pip install --upgrade pip && pip install -r requirements.txt
