FROM ubuntu:latest AS builder1

RUN apt-get update && \
    apt-get install -y git build-essential cmake libboost-all-dev

WORKDIR /tikion
RUN git clone https://github.com/tikion/tikion.git . && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make

FROM rust:1.67 AS builder2
ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR
RUN apt update && apt install build-essential git curl python3-pip python3-dev ffmpeg libssl-dev libffi-dev -y
RUN pip install --upgrade --no-cache-dir pip && pip install --no-cache-dir -r requirements.txt
