FROM python:3.10-slim AS builder
RUN apt update && apt install build-essential curl -y
COPY ./requirements.txt .
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
#ENV PATH="/root/.cargo/bin:${PATH}"
RUN source "$HOME/.cargo/env"
RUN pip install --upgrade --no-cache-dir pip && pip install --no-cache-dir -r requirements.txt
FROM python:3.10-slim
ENV WORKDIR /app
WORKDIR $WORKDIR
ADD . $WORKDIR
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
